All functions are added
VladimirNalivaiko/Number-Extension pull request #1
Opened 2017-09-29 17:21 UTC by VladimirNalivaiko

2017-10-02 00:18 UTC, paveldz requested changes

2017-10-02 00:18 UTC, paveldz commented on js/main.js
> +    var result = this;
please use Math.pow function

2017-10-02 10:19 UTC, VladimirNalivaiko commented on js/main.js
> +    var result = this;
ok

2017-10-03 16:06 UTC, paveldz approved these changes

2017-10-05 07:57 UTC, merged